version: "3.6"
services:
  gateway:
    image: "maven:3.8.3-jdk-11"
    #command: "bash -c \"echo Pass\""
    command: "bash -c \"mvn clean package\""
    volumes:
    - ./gateway:/usr/src/app
    - $HOME/.m2:/root/.m2
    working_dir: "/usr/src/app"
  users:
    image: "maven:3.8.3-jdk-11"
    #command: "bash -c \"echo Pass\""
    command: "bash -c \"mvn clean package\""
    volumes:
    - ./users:/usr/src/app
    - $HOME/.m2:/root/.m2
    working_dir: "/usr/src/app"
  security:
    image: "maven:3.8.3-jdk-11"
    #command: "bash -c \"echo Pass\""
    command: "bash -c \"mvn clean package\""
    volumes:
    - ./security:/usr/src/app
    - $HOME/.m2:/root/.m2
    working_dir: "/usr/src/app"
  inventory:
    image: "maven:3.8.3-jdk-15"
    command: "bash -c \"mvn clean package\""
    volumes:
    - .:/usr/src/app
    - $HOME/.m2:/root/.m2
    working_dir: "/usr/src/app/inventory"